Try: load Tiny using filters
ClassicPress-research/ClassicPress-Editor pull request #29
Opened 2021-09-03 03:57 UTC by joyously

Rename `scripts` to `js` and `tinymce5` to `tinymce` to match core, then use filters to control where the core loads from (plugin folder instead of wp-includes).

There is still some breakage, and _something_ is preventing the toolbar from showing in Visual mode. (I don't see it at all in the source code.)

2021-09-05 22:13 UTC, joyously commented
I have found that the 5.x orders the editor HTML differently than 4.x.
4.x shows the two toolbars and then the two editors 
but 5.x shows text toolbar and textarea, then the bare bones of the visual toolbar and the iframe.

They changed a lot of the class names (from a `mce` prefix to a `tox` prefix). Despite patching the major old class names in to the correct spots, having a different order is likely affecting the JS in `expand-editor.js` and could affect the CSS.

2021-09-07 01:37 UTC, joyously commented
@johnalarcon I got the Visual toolbar working finally.
This version has `resize: true` and neither autoresize nor wpautoresize loaded because they both have a problem with the switch from Text to Visual mode. Now that I found the 4.1 version autoresize that is so close to wpautoresize, I can understand better what to change for 5.x.
There are still plugins to fix, but that is for other PRs. This PR is about how the editor is loaded.

2021-09-07 16:28 UTC, joyously commented
This PR should fix issues 
#3  
#4 (the button is not loaded)
#6 (the toolbar rows are separate)
probably #8 (standard loading is used, but I don't know how to test issue)
#9 (no extra buttons loaded)
#10 
#11 
#12 (switching modes still has a problem)
#16 
#20 (complicated buttons might need some fixes)

2021-09-07 16:42 UTC, joyously commented
This PR would affect closed issues
likely 13, but not tested (standard loading is used for the editor)
14 (popup at cursor) would be fixed
15 (word count) would be fixed
17 (editor showing in other places) would be fixed
18 (syntax highlighter) **would be undone**
30 (screen option) full height is still broken but distraction free would be fixed

2021-09-07 18:30 UTC, johnalarcon commented
Awesome job, @joyously – thanks for your help on this. There's a couple slight issues; I'm reviewing now.

2021-09-07 18:44 UTC, johnalarcon requested changes
Joy, nice work on this. I've added a few comments. Also, do we need the compat3x code still after this PR?

2021-09-07 18:44 UTC, johnalarcon commented on classicpress-editor.php
> +//namespace ClassicPress\TinyMce5;
Is there a reason the namespacing was commented out?

2021-09-07 18:44 UTC, johnalarcon commented on classicpress-editor.php
> +add_filter( 'includes_url', 'try_tinymce5', 10, 2 );
These several functions can be converted to methods, and the `add_filter` calls can go into the constructor.

2021-09-07 18:44 UTC, johnalarcon commented on classicpress-editor.php
> +global $tinymce_version;
This can go at the top of the constructor.

2021-09-07 18:44 UTC, johnalarcon commented on classicpress-editor.php
>  		wp_enqueue_style('classicpress-editor',    plugin_dir_url(__FILE__).'styles/classicpress-editor.css');
I think we should also change references like this to `css` to be inline with how it will be in core, and rename the `styles` directory for consistency.

2021-09-07 18:44 UTC, johnalarcon commented on classicpress-editor.php
> +		wp_enqueue_script('classicpress-tinymce5', plugin_dir_url(__FILE__).'js/tinymce/tinymce.min.js');
Particularly during development, script/style enqueuing should have `time()` used for the version to ensure that every page load is pulling the very latest code and not serving a cached file.

2021-09-07 18:44 UTC, johnalarcon commented on js/tinymce/wp-tinymce.php
> +$expires_offset = 31536000; // 1 year
Let's use a clarifying constant here. `YEAR_IN_SECONDS`

2021-09-07 19:10 UTC, joyously commented on classicpress-editor.php
> +//namespace ClassicPress\TinyMce5;
Yes, because I wanted to remove your code and I couldn't if I left the namespace there.

2021-09-07 19:10 UTC, joyously commented on classicpress-editor.php
> +add_filter( 'includes_url', 'try_tinymce5', 10, 2 );
They could, but this was a PoC. I wanted to make sure none of your code would run.

2021-09-07 19:11 UTC, joyously commented on classicpress-editor.php
> +global $tinymce_version;
As this PR shows, there is no class needed, so no constructor needed.

2021-09-07 19:14 UTC, joyously commented on classicpress-editor.php
>  		wp_enqueue_style('classicpress-editor',    plugin_dir_url(__FILE__).'styles/classicpress-editor.css');
I expect that all the original code would be removed, so the point is moot. That code is not executed. (the name change of scripts to js here was just for consistency and the ability to continue to run it the original way)

2021-09-07 19:15 UTC, joyously commented on classicpress-editor.php
> +		wp_enqueue_script('classicpress-tinymce5', plugin_dir_url(__FILE__).'js/tinymce/tinymce.min.js');
This code doesn't execute in my version. (name change was just for consistency and continued testing)

2021-09-07 19:15 UTC, joyously commented on js/tinymce/wp-tinymce.php
> +$expires_offset = 31536000; // 1 year
This was unchanged from core.

2021-09-07 19:24 UTC, joyously commented
> do we need the compat3x code still after this PR?

I ran tests both with and without it. It patches some events that core scripts use that would need to be changed in core (and any plugins), so as a whole, more things work with it than without it.

2021-09-07 23:12 UTC, johnalarcon approved these changes

2021-09-07 23:24 UTC, johnalarcon approved these changes

2021-09-07 23:48 UTC, merged