update editor-expand.js
ClassicPress-research/ClassicPress-Editor pull request #60
Opened 2021-09-15 22:48 UTC by joyously

Fix the JS errors from the missing functions in editor-expand.js.
part of #53 

The old button function has a `classes` key, that is not used by the new function.

2021-09-15 23:06 UTC, johnalarcon requested changes
The version bump is fine to accompany with this PR, but, the other edits to `classicpress-editor.php` should be changed back as they are unrelated to changing the `editor-expand.js` target file.

2021-09-15 23:06 UTC, johnalarcon commented on classicpress-editor.php
> +		add_filter( 'script_loader_src', [ $this, 'filter_editor_expand_url' ], 10, 2 );
This line (and the corresponding method) are the only changes in this file related to the change at hand.

2021-09-15 23:10 UTC, joyously commented on classicpress-editor.php
> +		add_filter( 'script_loader_src', [ $this, 'filter_editor_expand_url' ], 10, 2 );
Well, I was cleaning up from the unreviewed commits and reverts you did earlier.

2021-09-15 23:11 UTC, johnalarcon commented on classicpress-editor.php
> +		add_filter( 'script_loader_src', [ $this, 'filter_editor_expand_url' ], 10, 2 );
Point taken. They weren't reviewed, but, they were separate. :)

2021-09-16 00:54 UTC, johnalarcon approved these changes
I appreciate your moving this. This is a crap title, though – it doesn't indicate what is being accomplished. Please don't use titles like this in the future.

2021-09-16 00:55 UTC, johnalarcon approved these changes

2021-09-16 00:55 UTC, johnalarcon approved these changes

2021-09-16 05:23 UTC, merged